### ISSUE TITLE
matrix D in quadratic function is not positive definite!

### ISSUE THREAD

**Issue by Ulawun** [albertosantini/node-finance#4]
Hi Alberto,

Great repo, thanks a lot.
The only reason, why I cannot use it, is the error:
"matrix D in quadratic function is not positive definite!".
I tried applying node-finance to normal stock portfolios.
I think, I should not be the only one having this issue.
Do you get this message as well ?
Is it a principal problem,
or is there any work around ?
I think you took the approach from R.
Does R have the same issue ?
Are there alternative NodeJS solutions ?

Thanks in advance

**Comment by albertosantini** [comment]
Thanks for the feedback.

`finance` package uses, behind the scenes, to optimize the portfolio a quadratic programming approach,
implemented by `quadprog` module.

`quadprog` module is a porting from R package `quadprog` 
It solves the quadratic programming problem only when the matrix D is positive definite.

You may give a look at `conpa`, an asset allocation web app, to use correctly it.

The figures are always double checked against R package `quadprog`, used in the method `portfolio.optim` of the R package `tseries`.

It is an issue only if the figures are different from R implementation.
So, using the same inputs, you should obtain the same results with `node-finance` and `portfolio.optim` in R.
